name: Update Plots

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write
  pages: write

jobs:
  update-plots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas plotly numpy

      - name: Run analysis and update plots
        run: |
          mkdir -p plots
          python BIDs/BIDs_analysis.py
        
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Commit and push if changed
        run: |
          git add plots/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update plots with responsive design" && git push origin main) 